services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=pitch_insight_hub.settings.development
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_FOOTBALL_KEY=${API_FOOTBALL_KEY}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=p${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
volumes:
  postgres_data:
