# Generated by Django 3.2.10 on 2024-10-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_league_season_seasonteam_team'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='league',
            table='leagues',
        ),
        migrations.AlterModelTable(
            name='season',
            table='seasons',
        ),
        migrations.AlterModelTable(
            name='seasonteam',
            table='season_teams',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('round', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('score', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='analytics.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='analytics.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.season')),
            ],
            options={
                'db_table': 'fixtures',
            },
        ),
    ]
