# Generated by Django 3.2.10 on 2024-10-20 19:41

from django.db import migrations
from utils.sql_functions import get_form_guide_function_sql


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20241018_2204'),
    ]

    operations = [
        migrations.RunSQL(
            sql=get_form_guide_function_sql(),
            reverse_sql='DROP FUNCTION IF EXISTS calculate_form_guide(INT, INT);'
        ),
    ]
